### ISSUE TITLE
Updates on Flags don't trigger push

### ISSUE THREAD

**Issue by heinlein-support** [st3fan/dovecot-xaps-plugin#17]
If the client changes a message flag from "unread" to "read" the client will do an update on the flags by IMAP.

Looks like this event isn't captured from xaps-plugin. 

The clients don't get an push notification, so they don't update their cache and the message stays marked as unread untill the next manual sync is done.

**Comment by freswa** [comment]
@heinlein-support  This plugin works via lmtp so local changes in the maildir are atm not supported

**Comment by heinlein-support** [comment]
@freswa  Yes, but there can also be relevant changes made by IMAP so the plugin must be extend to work also as an IMAP plugin to cover all changes. If not, the result is not reliable and not complete from a user's point of view.

**Comment by freswa** [comment]
@heinlein-support Sending a push notification on every mark/move is way to expensive. iOS [throttles push notifications](https://developer.apple.com/documentation/fileprovider/content_and_change_tracking/tracking_your_file_provider_s_changes/using_push_notifications_to_signal_changes?language=objc) for apps when they [drain to much battery](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application). 

> The system tracks the elapsed time, power usage, and data costs for your app’s background downloads. Apps that use significant amounts of power when processing remote notifications may not always be woken up early to process future notifications.

So you may implement it, but it won't work as expected and would lead to a more confusing and incomplete behavior than now.
Besides that, [Apple also does not send push notifications for anything but new messages in iCloud](https://support.apple.com/en-ca/HT203545).

**Comment by heinlein-support** [comment]
@freswa Yes, I know an I understand that. Totally.

But our users (not just one) started huge discussions in our public forum also blaming us, for not sending right notifications.

They're using an account on an iphone and an ipad at the same time. If they read an email on device 1 the device 2 will show "new unread e-mails" four hours or untill they're starting a manual update on device 2. They expect that device 2 will update his message status without manual interaction.

**Comment by freswa** [comment]
@heinlein-support You may consider using the Microsoft Exchange Protocol, I think the features you are looking for are supported there. If you insist on using native push, you may implement some custom logic to send a push notification when there have been no new mails for some time (e.g. 5/10 minutes) AND there have been marks/moves after the last new mail. You would avoid too many notifications but that would probably lead to some side effects, so no guarantee on that one.

**Comment by heinlein-support** [comment]
@freswa  Oh no, we introduced xapsd to get rid of the Exchange Protocol for Apple Users...

Yes, adding a "timed cache" in xapsd to sync "low priority" changes just every 30 minutes at once could be a good solution. But I'm not able to code in GO...

**Comment by freswa** [comment]
Fixed with #31
