### ISSUE TITLE
Dovecot 2.2 ostream-unix

### ISSUE THREAD

**Issue by MaFL2k** [st3fan/dovecot-xaps-plugin#28]
Hi, is ostream-unix supported for dovecot <2.3?  
I can´t find it in the sources until 2.3rc1. Or do I have to manually merge it?

**Comment by stephanbosch** [comment]
What do you mean?
https://github.com/dovecot/core/blob/master-2.2/src/lib/ostream-unix.c

**Comment by freswa** [comment]
It's implemented at least since 2.2.31
