### ISSUE TITLE
Dovecot > 2.2.19 ostream-unix.h

### ISSUE THREAD

**Issue by robinwit** [st3fan/dovecot-xaps-plugin#29]
I'm running Ubuntu 16.04.3 LTS with Dovecot 2.2.22 (fe789d2) and I'm getting `xaps-daemon.c:29:26: fatal error: ostream-unix.h: No such file or directory`.
It seems ostream-unix was only introduced in dovecot 2.2.31?

**Comment by robinwit** [comment]
Compilation is fixed now, but the plugin doesn't seem to be able to read from the socket:

`Feb  4 15:39:37 mail dovecot: imap(robin@example.com): Error: net_connect_unix(/tmp/xapsd.sock) failed: No such file or directory
`

**Comment by freswa** [comment]
Please post the output of ```doveconf -n```

**Comment by robinwit** [comment]
`# 2.2.22 (fe789d2): /etc/dovecot/dovecot.conf
# Pigeonhole version 0.4.13 (7b14904)
# OS: Linux 4.4.0-104-generic x86_64 Ubuntu 16.04.3 LTS ext4
auth_mechanisms = plain login
first_valid_uid = 150
last_valid_uid = 150
mail_gid = mail
mail_location = maildir:/var/vmail/%d/%n
mail_uid = vmail
namespace inbox {
  inbox = yes
  location = 
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
  prefix = 
}
passdb {
  args = /etc/dovecot/dovecot-sql.conf.ext
  driver = sql
}
plugin {
  push_notification_driver = xaps
  xaps_socket = /tmp/xapsd.sock
}
postmaster_address = postmaster@example.com
protocols = " imap pop3"
service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = postfix
    mode = 0666
    user = postfix
  }
  unix_listener auth-userdb {
    group = mail
    mode = 0666
    user = vmail
  }
}
ssl_cert = </etc/letsencrypt/live/example.com/fullchain.pem
ssl_cipher_list = ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
ssl_dh_parameters_length = 2048
ssl_key = </etc/letsencrypt/live/example.com/priv	.pem
ssl_prefer_server_ciphers = yes
ssl_protocols = !SSLv2 !SSLv3
userdb {
  args = /etc/dovecot/dovecot-sql.conf.ext
  driver = sql
}
protocol lmtp {
  mail_plugins = " notify push_notification push_notification_xaps"
}
protocol lda {
  mail_plugins = " notify push_notification push_notification_xaps"
}
protocol imap {
  mail_plugins = " imap_xaps notify push_notification push_notification_xaps imap_xaps"
}
`

I'm running the daemon like this:

`./xapsd -key=/home/robin/key.pem -certificate=/home/robin/certificate.pem   -database=/home/robin/xapsd.json -socket=/tmp/xapsd.sock`

**Comment by freswa** [comment]
Thanks, the config seems ok. What are the permissions of /tmp/xapsd.sock?

**Comment by robinwit** [comment]
I've even chmod'ed it to 777. 
I'm not too experienced with sockets unfortunately.
This is the only output I get from the daemon, ever:
```
2018/02/04 19:09:53 Starting xapsd 1.0b1 on /tmp/xapsd.sock
```

**Comment by freswa** [comment]
So what gives a ```ls -lah /tmp/xapsd.sock``` after you start the daemon?

**Comment by robinwit** [comment]
```
srwxrwxrwx 1 root root 0 Feb  4 19:09 /tmp/xapsd.sock
```

**Comment by freswa** [comment]
How do you start dovecot and xapsd? Does anyone of them has a systemd private root?

**Comment by robinwit** [comment]
My setup should be pretty standard I think, no systemd, everything is installed from the default apt packages on 16.04.3. So it's just `service restart dovecot`.
xapsd is started with: `./xapsd -key=/home/robin/key.pem -certificate=/home/robin/certificate.pem -database=/home/robin/xapsd.json -socket=/tmp/xapsd.sock`.

**Comment by freswa** [comment]
What about AppArmor? Is it installed? You should try a different location for the socket.

**Comment by freswa** [comment]
And please double check your init system. The dovecot-core package for xenial contains this:
```
# This file is part of Dovecot
#
# If you want to pass additionally command line options to the dovecot
# binary, create the file:
# 	`/etc/systemd/system/dovecot.service.d/service.conf'.
# In this file create a Service section and configure an Environment with
# the variable `OPTIONS'. For example:
#
#	[Service]
#	Environment='OPTIONS=-p'
#
# In the `Service' section you may also specify various other setting.
# If you have trouble with `Too many open files' you may set:
#LimitNOFILE=8192
#
# If you want to allow the Dovecot services to produce core dumps, use:
#LimitCORE=infinity

[Unit]
Description=Dovecot IMAP/POP3 email server
Documentation=man:dovecot(1)
Documentation=http://wiki2.dovecot.org/
After=local-fs.target network.target

[Service]
Type=forking
ExecStart=/usr/sbin/dovecot
PIDFile=/var/run/dovecot/master.pid
ExecReload=/usr/bin/doveadm reload
ExecStop=/usr/bin/doveadm stop
PrivateTmp=true
NonBlocking=yes
# Enable this if your systemd is new enough to support it:
#ProtectSystem=full

[Install]
WantedBy=multi-user.target
```

**Comment by robinwit** [comment]
<insert sweat words here>
The /tmp was indeed the problem. Maybe it should be removed from the daemon README.
Danke sehr für die Hilfe on this Sunday evening! Have a good start of the week tomorrow. 😊

**Comment by freswa** [comment]
You're welcome. So the rootproblem is the PrivateTmp of the systemd service file of dovecot which creates a new fs namespace for /tmp.
I'll check the README.
