### ISSUE TITLE
undefined symbol: push_notification_driver_debug

### ISSUE THREAD

**Issue by jpenney** [st3fan/dovecot-xaps-plugin#32]
I tried updating to the latest code, and I'm getting the following in my logs:

```
Error: Couldn't load required plugin /usr/lib/dovecot/modules/imap_xaps_plugin.so: dlopen() failed: /usr/lib/dovecot/modules/imap_xaps_plugin.so: undefined symbol: push_notification_driver_debug
```

**Comment by freswa** [comment]
Please post the output of ```doveconf -n```, what version of dovecot and which distro you run.

**Comment by jpenney** [comment]
I'm running Ubuntu 16.04.3 LTS, with dovecot version 2.2.22.

I commented out the calls to `push_notification_driver_debug` and the error went away.  Where is that function defined?

**Comment by freswa** [comment]
Please post the output of ```doveconf -n``` so I can have a look at it. Thanks

**Comment by jpenney** [comment]
I'm not real comfortable posting the whole output. Is there either a specific set of things you need to see, or a way I can email it to you?

**Comment by freswa** [comment]
No problem. everything secret should be omitted by doveconf, but if you feel more comfortable you can email the config via email (address is in my github profile).

**Comment by jpenney** [comment]
Sent to the email in the license file (I couldn't see one on your github profile page).

**Comment by freswa** [comment]
Sorry, that's not me :)
Would you mind to send it again to frederik dot schwan at linux dot com? Thanks

**Comment by jpenney** [comment]
Oh, whoops! Done. (sorry @st3fan)

**Comment by freswa** [comment]
I hope I got the problem...
Your line:
```
protocol imap {
 [...]
 mail_plugins = notify mail_log fts fts_solr antispam imap_xaps
}
```
But imap_xaps uses symbols of push_notification too. Since it's not loaded you can't load an object that references it. That's why the default config includes a line like it:
```
notify push_notification push_notification_xaps
```
That should fix your problem.

**Comment by jpenney** [comment]
Yeah, that did it (don't get any notifications any more, but that must be a different issue).

I thought, based on the comments in `xaps.conf`, that I was supposed to use one of these two sections. I guess not.

```
# push notifications for incoming messages only
protocol imap {
  mail_plugins = $mail_plugins imap_xaps
}
# push notifications also for /seen /unseen /flag etc.
protocol imap {
  mail_plugins = $mail_plugins notify push_notification push_notification_xaps imap_xaps
}
```

**Comment by freswa** [comment]
This is a good point and definitely my fault - will fix the default config asap
