### ISSUE TITLE
When will there be release 0.7?

### ISSUE THREAD

**Issue by golodhrim** [st3fan/dovecot-xaps-plugin#43]
Hey there?

as archlinux (https://aur.archlinux.org/packages/dovecot-xaps-plugin) refers to version 0.7, my question is, if there is any release named 0.7 or if there was a release 0.7, if not, I guess, we need to fix it in arch, else, it would be awesome to get it fixed here.

Thanks

**Comment by freswa** [comment]
Just published 0.8
